hell = {
	'burn' : 'BURN BURN BURN BURN',
	'calc' : "It's a calculator",
	'chat' : "Chat with Kiyohime. Don't die.",
	'clone' : 'Copies people or sumn idk',
	'CompoundId' : 'get compound by id',
	#'connect' : 'vc',
	'danbooru' : 'Finds an image on danbooru',
	'dm' : 'dms a person i guess',
	'disconnect' : 'disconnects.',
	'download' : 'Downloads file from cloud server',
	'embed' : 'Embeds whatever you say',
	'google' : 'google.',
	'kiyo' : 'poops out kiyo pics',
	'latest' : 'shits out latest kiyo pic',
	'list' : 'Lists down every file on the cloud',
	'multi' : 'Finds multiple images on danbooru',
	'mp3' : 'Generates an mp3 file of whatever you type',
	'nwordcount' : 'counts your racism',
	'pick' : 'Chooses randomly from a list',
	'ping' : 'pong',
	'poll' : 'democracy',
	'RandomCompound' : 'get a random compound',
	'say' : 'yes',
	'SearchCompound' : 'search chemistry compounds',
	'step' : 'NO STEP ON SNEK',
	'translate' : 'Translates stuff',
	'trash' : 'dumps a cloud file to trash',
	'tts' : 'yesser',
	'ud' : 'searches the urbandictionary',
	'upload' : 'Uploads file to a cloud server',
	'word' : "Generates a word that doesn't exist",
	'wordcloud' : 'Generates a wordcloud of the server',
	'yeet' : 'Posts the link to a custom emote',
	'youtube' : 'Searches youtube vids',
	'ytdl' : 'ytdl, kinda broken',
}
