hell = {'kiyo' : 'poops out kiyo pics',
'burn' : 'BURN BURN BURN BURN',
'step' : 'NO STEP ON SNEK',
'upload' : 'Uploads file to a cloud server',
'download' : 'Downloads file from cloud server',
'list' : 'Lists down every file on the cloud',
'multi' : 'Finds multiple images on danbooru',
'danbooru' : 'Finds an image on danbooru',
'say' : 'yes',
'tts' : 'yesser',
'connect' : 'vc',
'nwordcount' : 'counts your racism',
'door' : 'door',
'dm' : 'dms a person i guess',
'latest' : 'shits out latest kiyo pic',
'trash' : 'dumps a cloud file to trash',
'disconnect' : 'disconnects.',
'google' : 'google.',
'calc' : 'calculates shit',
'ping' : 'pong'
}
