hell = {'kiyo' : 'poops out kiyo pics',
'burn' : 'BURN BURN BURN BURN',
'step' : 'NO STEP ON SNEK',
'upload' : 'Uploads file to a cloud server',
'download' : 'Downloads file from cloud server',
'list' : 'Lists down every file on the cloud',
'multi' : 'Finds multiple images on danbooru',
'danbooru' : 'Finds an image on danbooru',
'say' : 'yes',
'tts' : 'yesser',
'connect' : 'vc',
'nwordcount' : 'counts your racism',
'door' : 'door',
'dm' : 'dms a person i guess',
'latest' : 'shits out latest kiyo pic',
'trash' : 'dumps a cloud file to trash',
'disconnect' : 'disconnects.',
'google' : 'google.',
'ping' : 'pong',
'chat' : "Chat with Kiyohime. Don't die.",
'word' : "Generates a word that doesn't exist",
'wordcloud' : 'Generates a wordcloud of the server',
'calc' : "It's a calculator",
'clone' : 'Copies people or sumn idk',
'embed' : 'Embeds whatever you say',
'mp3' : 'Generates an mp3 file of whatever you type',
'pick' : 'Chooses randomly from a list',
'poll' : 'democracy',
'translate' : 'Translates stuff',
'ud' : 'searches the urbandictionary',
'yeet' : 'Posts the link to a custom emote',
'youtube' : 'Searches youtube vids',
'ytdl' : 'ytdl, kinda broken',
'SearchCompound' : 'search chemistry compounds'
}
